name: Build

on:
  push:
    branches: ['**']
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - uses: actions/setup-node@v6.2.0
        with:
          node-version: 24

      - uses: actions/cache@v5.0.3
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --production

      - uses: actions/cache@v5.0.3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextcache-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.ts', '**/*.tsx', '**/*.css') }}
          restore-keys: |
            ${{ runner.os }}-nextcache-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-nextcache-

      - name: Build Next.js
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.12.0

      - name: Build Docker image
        uses: docker/build-push-action@v6.19.2
        with:
          context: .
          file: Dockerfile.ci
          push: false
          tags: docker-demo:with-cache
